config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController


    before_action :set_book, only: [:show , :edit, :update, :destroy]

    def home
    
    end

    def about
    end


    def show
        # @book = Book.find(params[:id])
    end

    def index
        @book = Book.all
    end

    def new
        @book = Book.new
    end

    def edit
        # @book = Book.find(params[:id])
    end



    def create
        @book = Book.new(book_params)
        if @book.save
            flash[:notice] = "Book created succesfully"
            redirect_to book_path(@book) #it will redirect to show page or also we can write "redirect_to @article" both will work the same way
        else
            render :new, status: :unprocessable_entity
        end
    end


    def update
        # @book = Book.find(params[:id])
        if @book.update(book_params)
            flash[:notice] = "Book updated succesfully"
            redirect_to @book
        else
            render :edit , status: :unprocessable_entity
        end
    end

    def destroy
        # @book = Book.find(params[:id])
        @book.destroy
        redirect_to books_path
    end

    private

    def set_book
        @book = Book.find(params[:id])
    end

    def book_params
        params.require(:book).permit(:name,:description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_form.html.erb
<% if @book.errors.any? %>
    <h1> You have errors</h1>
    <ul>
    <% @book.errors.full_messages.each do |msg|%>
        <li><%=msg%> </li>
    <%end%>
    </ul>
<% end %>

<%= form_with(model: @book) do |f|%>

    <p>
        <%= f.label :name %> <br>
        <%= f.text_field :name %>
    </p>

    <p>
        <%= f.label :description%><br>
        <%=f.text_area :description%>
    </p>
    <p>
        <%= f.submit%>
    </p>
<% end %>

app/views/books/edit.html.erb
<h1> Edit your profile </h1>

<%= render 'form'%>

app/views/books/index.html.erb
<h1 > List of all Books</h1>

<%= link_to "create new book", new_book_path  %>

<%= @book.each do |item|%>  
<h2 > Name : <%= item.name%></h2>
<p >  Description :<%= item.description %></p>
<%= link_to "View", book_path(item) %>
<%= link_to "Edit" , edit_book_path(item) %>
<%= link_to "delete" , book_path(item),data: { "turbo-method": :delete , "turbo-confirm": "Are you sure ?"} %>

<% end%>

app/views/books/new.html.erb
<h1> Create new Article </h1>

<%= render 'form'%>


<%# <%= link_to "Back to atricles", articles_path %>

app/views/books/show.html.erb
<h1> Show the book </h1>
<p> <strong> name : </strong> <%= @book.name %> </p> 
<p> <strong> Description : </strong> <%= @book.description%> </p> 


<%= link_to "Back to books", books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrudAssignment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>